linters:
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused
  disable:
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 10
