linters:
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused
  disable:
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 10

issues:
  exclude-rules:
    # This global variable is part of the API.
    - path: "testgroup\\.go"
      source: "^var RunInParallelParentTestName = "
      linters:
        - gochecknoglobals
